// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuJShhDFvUMx5kiaOJAS3hf9prhnyqijk',
    appId: '1:850456401538:web:2131f31406a1e7d362c69b',
    messagingSenderId: '850456401538',
    projectId: 'thrifty-099',
    authDomain: 'thrifty-099.firebaseapp.com',
    storageBucket: 'thrifty-099.firebasestorage.app',
    measurementId: 'G-K1FSNV7WQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJW9FbNfsok30ux24EdQnbqa6WPvI8KPk',
    appId: '1:850456401538:android:fe54279e4ac3c67f62c69b',
    messagingSenderId: '850456401538',
    projectId: 'thrifty-099',
    storageBucket: 'thrifty-099.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5gKFCRy2ch1yzV1pzQ_ischMQaCpA54o',
    appId: '1:850456401538:ios:f4f5f1adb6934e2862c69b',
    messagingSenderId: '850456401538',
    projectId: 'thrifty-099',
    storageBucket: 'thrifty-099.firebasestorage.app',
    iosBundleId: 'com.example.dealura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5gKFCRy2ch1yzV1pzQ_ischMQaCpA54o',
    appId: '1:850456401538:ios:f4f5f1adb6934e2862c69b',
    messagingSenderId: '850456401538',
    projectId: 'thrifty-099',
    storageBucket: 'thrifty-099.firebasestorage.app',
    iosBundleId: 'com.example.dealura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuJShhDFvUMx5kiaOJAS3hf9prhnyqijk',
    appId: '1:850456401538:web:85626de9bd4454e662c69b',
    messagingSenderId: '850456401538',
    projectId: 'thrifty-099',
    authDomain: 'thrifty-099.firebaseapp.com',
    storageBucket: 'thrifty-099.firebasestorage.app',
    measurementId: 'G-3ZSPGY5PT7',
  );
}
